version: '3'
services:
  app:
    build: .
    environment:
      - DB_HOST=your-db-host
      - DB_PORT=3306
      - DB_USERNAME=your-username
      - DB_PASSWORD=your-password
      - DB_DATABASE=todolist
    ports:
      - '3000:3000'
