on:
  workflow_run:
    workflows: [develop]
    types: [completed]
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      # 下载构建产物
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      # 部署步骤...
