on:
  push:
    branches: [develop]
jobs:
  develop:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: development
      deploy_dir: /www/wwwroot/todo-list-server/develop
    secrets:
      SERVER_KEY: ${{ secrets.SERVER_KEY }}
      SERVER_USER_NAME: ${{ secrets.SERVER_USER_NAME }}
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
