on:
  push:
    branches: [main]
jobs:
  main:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
      deploy_dir: /www/wwwroot/todo-list-server/release
    secrets:
      SERVER_KEY: ${{ secrets.SERVER_KEY }}
      SERVER_USER_NAME: ${{ secrets.SERVER_USER_NAME }}
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
