on:
  push:
    branches: [main]
jobs:
  pre-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Special production tasks
        run: echo "Running production-specific tasks"

  deploy:
    needs: pre-deploy
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: production
      deploy_dir: /www/wwwroot/chat-server/release
    secrets:
      SERVER_KEY: ${{ secrets.SERVER_KEY }}
      SERVER_USER_NAME: ${{ secrets.SERVER_USER_NAME }}
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
